// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"time"
)

type Account struct {
	IDAccount int64
	Owner     string
	Balance   string
	Currency  string
	CreateAt  time.Time
}

type Entry struct {
	IDEntries int64
	IDAccount int64
	Amount    int64
	CreateAt  time.Time
}

type Transfer struct {
	IDTransfer    int64
	FromIDAccount int64
	ToIDAccount   int64
	Amount        int64
	CreateAt      time.Time
}
